import {
    Accessibility,
    AirVent,
    ArrowUpDown,
    Bath,
    BellRing,
    Bike,
    Building,
    Car,
    Dumbbell,
    Fence,
    Laptop,
    Microwave,
    Package,
    PhoneCall,
    Refrigerator,
    Sun,
    Trees,
    Tv,
    Utensils,
    Waves,
    Wind,
    WashingMachine,
    Wifi,
    type LucideIcon,
} from 'lucide-react';
import type { PropertyAmenity } from '@/types';

/** Icône par équipement, pour lire la liste d'un coup d'œil. */
export const propertyAmenityIcons: Record<PropertyAmenity, LucideIcon> = {
    elevator: ArrowUpDown,
    balcony: Building,
    terrace: Fence,
    wifi: Wifi,
    washing_machine: WashingMachine,
    dishwasher: Utensils,
    oven: Refrigerator,
    tv: Tv,
    air_conditioning: AirVent,
    parking: Car,
    cellar: Package,
    garden: Trees,
    dryer: Wind,
    microwave: Microwave,
    bathtub: Bath,
    intercom: PhoneCall,
    concierge: BellRing,
    natural_light: Sun,
    double_glazing: Waves,
    wheelchair_access: Accessibility,
    bike_storage: Bike,
    workspace: Laptop,
    gym: Dumbbell,
    pool: Waves,
};
